services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12991453
      POSTGRES_DB: gibi
    volumes:
      - /mnt/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [CMD-SHELL, pg_isready -U postgres -d gibi]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  app:
    image: node:20
    working_dir: /app
    environment:
      COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"
      NODE_ENV: development
      npm_config_production: false
    volumes:
      - ./:/app
    env_file:
      - .env
    command:
      - bash
      - -lc
      - |
          corepack enable && corepack prepare pnpm@9 --activate && \
          pnpm install --no-frozen-lockfile && \
          pnpm prisma generate && \
          pnpm run api:dev
    ports:
      - 127.0.0.1:4000:4000
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
